
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int parentesis_B = 16;
  public static final int prIngresar = 26;
  public static final int parentesis_A = 15;
  public static final int mayor_o_igual = 19;
  public static final int Double = 62;
  public static final int imprimir = 57;
  public static final int con_parametros = 51;
  public static final int mod = 14;
  public static final int con = 68;
  public static final int hasta = 43;
  public static final int es_diferente = 22;
  public static final int hasta_que = 48;
  public static final int coma = 3;
  public static final int igual = 52;
  public static final int entonces = 38;
  public static final int multiplicacion = 11;
  public static final int corchete_B = 67;
  public static final int corchete_A = 66;
  public static final int fin_funcion = 50;
  public static final int repetir = 47;
  public static final int fin_metodo = 55;
  public static final int si = 32;
  public static final int divicion = 12;
  public static final int mientras = 45;
  public static final int nombre_variable = 29;
  public static final int es_igual = 21;
  public static final int menor_o_igual = 20;
  public static final int fin_si = 33;
  public static final int Falso = 64;
  public static final int menos = 10;
  public static final int menor = 18;
  public static final int fin_mientras = 46;
  public static final int EOF = 0;
  public static final int punto_coma = 31;
  public static final int prCadena = 7;
  public static final int mas = 59;
  public static final int prComo = 27;
  public static final int para = 42;
  public static final int fin_para = 44;
  public static final int error = 1;
  public static final int mayor = 17;
  public static final int prBoolean = 8;
  public static final int metodo = 54;
  public static final int or = 23;
  public static final int incremental = 69;
  public static final int Char = 65;
  public static final int prFin = 5;
  public static final int funcion = 49;
  public static final int prCaracter = 9;
  public static final int imprimir_nl = 58;
  public static final int potencia = 13;
  public static final int id = 2;
  public static final int interrogacion_B = 41;
  public static final int fin_segun = 39;
  public static final int interrogacion_A = 40;
  public static final int segun = 36;
  public static final int prCon_valor = 28;
  public static final int hacer = 37;
  public static final int String = 61;
  public static final int de_lo_contrario = 34;
  public static final int and = 24;
  public static final int not = 25;
  public static final int prInicio = 4;
  public static final int retornar = 53;
  public static final int Verdadero = 63;
  public static final int num = 60;
  public static final int o_si = 35;
  public static final int asignacion = 30;
  public static final int ejecutar = 56;
  public static final int prNumero = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "id",
  "coma",
  "prInicio",
  "prFin",
  "prNumero",
  "prCadena",
  "prBoolean",
  "prCaracter",
  "menos",
  "multiplicacion",
  "divicion",
  "potencia",
  "mod",
  "parentesis_A",
  "parentesis_B",
  "mayor",
  "menor",
  "mayor_o_igual",
  "menor_o_igual",
  "es_igual",
  "es_diferente",
  "or",
  "and",
  "not",
  "prIngresar",
  "prComo",
  "prCon_valor",
  "nombre_variable",
  "asignacion",
  "punto_coma",
  "si",
  "fin_si",
  "de_lo_contrario",
  "o_si",
  "segun",
  "hacer",
  "entonces",
  "fin_segun",
  "interrogacion_A",
  "interrogacion_B",
  "para",
  "hasta",
  "fin_para",
  "mientras",
  "fin_mientras",
  "repetir",
  "hasta_que",
  "funcion",
  "fin_funcion",
  "con_parametros",
  "igual",
  "retornar",
  "metodo",
  "fin_metodo",
  "ejecutar",
  "imprimir",
  "imprimir_nl",
  "mas",
  "num",
  "String",
  "Double",
  "Verdadero",
  "Falso",
  "Char",
  "corchete_A",
  "corchete_B",
  "con",
  "incremental"
  };
}

